// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/user').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.12.3_@opentelemetry+api@1.9.0_@types+node@20.14.9_eslint@9.6.0_sass@1.77.6_typescript@5.5.3_vite@5.3.3/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}